### ISSUE TITLE
Document best practices for adding fields to response (register_rest_field/register_meta) 

### ISSUE THREAD

**Issue by danielbachhuber** [WP-API/docs-v2#1]
We should communicate best practices for adding fields to responses.

Example requests:
- [Featured image in /posts as link instead of ID](https://github.com/WP-API/WP-API/issues/1147)

**Comment by kadamwhite** [comment]
Probably superseded by register_meta conversations that are ongoing

**Comment by kadamwhite** [comment]
Code sample for register_rest_field: https://core.trac.wordpress.org/ticket/38821#comment:4

**Comment by kadamwhite** [comment]
@kosso has provided code demonstrating register_rest_field as well: https://gist.github.com/kosso/47004c9fa71920b441f3cd0c35894409

and @tharsheblows has [provided this snippet for register_meta](https://wordpress.slack.com/archives/core-restapi/p1484645367002683), which is going to be added to the [code reference for register_meta](https://developer.wordpress.org/reference/functions/register_meta/) as a comment for now, and may be expanded in the handbook later:
```php
$object_type = 'post'; // The object type. For custom post types, this is 'post', for custom comment types, this is 'comment'.
$args1 = array(
    'type'             => 'string', // Validate and sanitize the meta value as a string. 
    // Note: currently (4.7) one of 'string', 'boolean', 'integer', 'number' must be used as 'type'. Default: 'string'. 
    'description'    => 'A meta key associated with a string meta value.', // Shown in the schema for the meta key.
    'single'        => true, // Return a single value of the type.
    'show_in_rest'    => true, // Show in the WP REST API response. Default: false.
);
register_meta( $object_type, 'my_postmeta_key', $args1 );

$args2 = array(
    'type'             => 'string', // Validate and sanitize the meta value as a string.
    // Note: currently (4.7) one of 'string', 'boolean', 'integer', 'number' must be used as 'type'. Default: 'string'. 
    'description'    => 'A meta key associated with a string meta value.', // Shown in the schema for the meta key.
    'single'        => false, // Return an array with the type used as the items type.
    'show_in_rest'    => true, // Show in the WP REST API response. Default: false.
);
register_meta( 'user', 'my_usermeta_key', $args2 );
```

**Comment by nylen** [comment]
This has been done for a couple of weeks.  https://developer.wordpress.org/rest-api/extending-the-rest-api/modifying-responses/
