### ISSUE TITLE
MIgration with old version

### ISSUE THREAD

**Issue by alaa-alsalehi** [WP-API/docs-v2#100]
I need to support the old version urls because of backward compatibility (I use this API on android mobile application) and I want to add new features exist on v2 of wp-api to my new versions
but when I download v2 I can not access routes and I got error with code json_no_route
can you suggest a solution? or there is a way to change v2 api url from wp-json/wp/v2/ to something else

**Comment by danielbachhuber** [comment]
You can use the `rest_url_prefix` [filter](https://developer.wordpress.org/reference/hooks/rest_url_prefix/) to change `wp-json` for v2, or the equivalent `json_url_prefix` filter to change the base for v1.
