### ISSUE TITLE
Action and filter reference

### ISSUE THREAD

**Issue by danielbachhuber** [WP-API/docs-v2#124]
We should build pages for each of our actions and filters.

**Comment by danielbachhuber** [comment]
cc @dannyb195

**Comment by danielbachhuber** [comment]
cc @brichards

**Comment by adamsilverstein** [comment]
I tried running the codebase thru the WP code parser https://github.com/WordPress/phpdoc-parser which is hook-aware - with pretty good result... not sure how helpful that is to this effort, still good to know that when merged with core we'll get good documentation from our inline docs.

**Comment by adamsilverstein** [comment]
cc: @rmccue 

parser export file: http://cl.ly/1A1R2g3U3r2l

can we leverage the parser/docs theme to build docs from inline documentation?

**Comment by BE-Webdesign** [comment]
I wrote a js script that grabs most things from the inline docs and puts it into #139 as markdown.  I should probably do it more the way you are doing it and have ruby generate the page as a sort of build process from json.

**Comment by rmccue** [comment]
@adamsilverstein We're not running WP on the site right now, but we can probably spin something up on the infrastructure that's already there for the demo.

@joehoyle Can we convert the demo site to multisite?

**Comment by joehoyle** [comment]
We that's easy enough, not sure exactly from this ticket what needs to go on that new site htough?

**Comment by kadamwhite** [comment]
@joehoyle @rmccue Do you think we need a dedicated page for this, or is the fact that these are now available in the code reference sufficient?

**Comment by rmccue** [comment]
I think the reference is sufficient.
