### ISSUE TITLE
Additional 3 plugins which utilizes the WP REST API v2

### ISSUE THREAD

**Issue by en-alis** [WP-API/docs-v2#129]
Hi,
I created 3 plugins which utilizes the WP REST API v2:
[WP REST API - Pure Taxonomies](https://wordpress.org/plugins/wp-rest-api-pure-taxonomies/)
[WP REST API - All Terms](https://wordpress.org/plugins/wp-rest-api-all-terms/)
[WP REST API - Post Type Taxonomies](https://wordpress.org/plugins/wp-rest-api-post-type-taxonomies/)

You can find all my rest-api plugins using "andrew-magik-rest-api" tag:
https://wordpress.org/plugins/tags/andrew-magik-rest-api

Would be nice, if you will add my plugins to the list with all other plugins from this page:
http://v2.wp-api.org/guide/plugins/

Thanks in advance!

**Comment by danielbachhuber** [comment]
Cool! Can you edit the page and submit a PR?

![image](https://cloud.githubusercontent.com/assets/36432/13877368/8cc8cabc-ecc7-11e5-8d50-4ac8521f7e9f.png)

**Comment by en-alis** [comment]
Thanks, I created pull request with my plugins:
https://github.com/WP-API/docs-v2/pull/130
