### ISSUE TITLE
Create a new post using REST API.

### ISSUE THREAD

**Issue by vikas009** [WP-API/docs-v2#133]
Hi I try  to make a app using AngualrJs and Ionic with wordpress REST API.
In this app  get the data from wordpress using wordpress REST API,

Now i try to create a new post through my app using REST API.

Its Give me the errror 

> {"code":"rest_cannot_create","message":"Sorry, you are not allowed to create new posts.","data":{"status":401}}

I also pass the header to and convert username and password to base64(YmxvYWdZXI6czdWx0QCNAIQ==) formet

> $http call $http.defaults.headers.common.Authorization = 'Basic YmxvYWdZXI6czdWx0QCNAIQ==';

**Comment by danielbachhuber** [comment]
You'll need to install and activate the [Basic Auth](https://github.com/WP-API/Basic-Auth) plugin in order to use Basic Auth. The WP REST API plugin only supports cookie auth out of the box.

**Comment by vikas009** [comment]
Hi thank for reply ,
I install the Basic Auth plugin in my wordpress .

Now i am facing same error 

> {"code":"rest_cannot_create","message":"Sorry, you are not allowed to create new posts.","data":{"status":401}}

Can you guide me some blog or Example for this?
