### ISSUE TITLE
Use absolute URLs for pages

### ISSUE THREAD

**Issue by danielbachhuber** [WP-API/docs-v2#14]
While the single page effect is nice, it makes it painful to add links and negatively impacts SEO. Let's switch to absolute URLs. It's a static website, so pageloads should be fast enough.

**Comment by rmccue** [comment]
Think this is fixed by #21. The links are technically relative, but can be changed if that's an issue by using `{{site.baseurl}}`

**Comment by danielbachhuber** [comment]
:+1: Looks good.
