### ISSUE TITLE
Ember.js Client

### ISSUE THREAD

**Issue by taras** [WP-API/docs-v2#140]
I just wanted to let you know that there is an Ember.js addon that makes it easy to use Ember as a client for WordPress REST API.

You can find it here https://github.com/oskarrough/ember-wordpress

You might want to consider adding it to your list of clients.

**Comment by kadamwhite** [comment]
Thanks for this, @taras, we've added it to the clients page at https://developer.wordpress.org/rest-api/using-the-rest-api/client-libraries/
