### ISSUE TITLE
Changes in new versión

### ISSUE THREAD

**Issue by pelayopc** [WP-API/docs-v2#145]
Now, with this request:
myblog.com/wp-json/wp/v2/categories
i get an html web from the blog, (index), no a json file, what must i do?
thx

example:
http://vigorizate.com/wp-json/wp/v2/categories/

**Comment by danielbachhuber** [comment]
Do other endpoints work as expected? Can you verify the plugin is installed and activated?

**Comment by pelayopc** [comment]
Yes installed and activated, dont works with other endpoints
http://vigorizate.com/wp-json/wp/v2/tags/
http://vigorizate.com/wp-json/wp/v2/posts/

all redirect to index

**Comment by danielbachhuber** [comment]
Ok. This problem is specific to your site, and is likely being caused by other code on the site or your server configuration.

It's hard to say what the exact problem might be without having access to your codebase, though. Sorry I can't be more helpful.
