### ISSUE TITLE
JSONP

### ISSUE THREAD

**Issue by alien315** [WP-API/docs-v2#150]
How can I make a JSONP call to the API?

Thanks

**Comment by rmccue** [comment]
The API supports a `_jsonp` parameter that can take a function name as a parameter (allowed characters are alphanumeric, `_` and `.`). This is one of a few "meta-parameters" supported by the API, indicated by the leading `_`.

We should document this better. :)

**Comment by kadamwhite** [comment]
@rmccue How would you imagine improving this documentation, beyond what we have in the https://developer.wordpress.org/rest-api/using-the-rest-api/global-parameters/ page?

**Comment by rmccue** [comment]
IIRC at the time, that page didn't exist (in any format), so should be good now 👍
