### ISSUE TITLE
New Tool: Compatible Plugins & Tools

### ISSUE THREAD

**Issue by EvanHerman** [WP-API/docs-v2#158]
Hey API team,

We've just released a new plugin that integrates with WP REST API v2, and would love to have it listed alongside the other compatible plugins & tools listed on the docs site.

Our Github repo is at:
https://github.com/yikesinc/wp-rest-api-controller

And the WordPress.org repo is at:
https://wordpress.org/plugins/wp-rest-api-controller/

The plugin essentially provides an interface for enabling/disabling end points on a per post type basis. It also allows for toggling/customizing the meta data displayed in the API requests.

Thanks,
Evan Herman

**Comment by BE-Webdesign** [comment]
Hi @EvanHerman,

Could you put these into a pull request for the plugins page in the docs?  Just follow the format that is already in https://github.com/WP-API/docs-v2/blob/gh-pages/guide/plugins/index.md and use the .org link.
