### ISSUE TITLE
Documentation: Getting Started: How to get additional information about a post with _embed

### ISSUE THREAD

**Issue by krogsgard** [WP-API/docs-v2#168]
Further explain _embed (or perhaps also move and rephrase current docs). Give example of when this is helpful, like replicating a singular post view. Show example of using embedded data.

**Comment by kadamwhite** [comment]
@krogsgard Where would you like this to live in the handbook? Is the documentation on [linking & embedding](https://developer.wordpress.org/rest-api/using-the-rest-api/linking-and-embedding/) sufficient, or should it be expanded?

**Comment by kadamwhite** [comment]
@krogsgard I'm closing this out, but please re-open if there's specific additions you think we should see
