### ISSUE TITLE
Better document how to consume API from within WP via PHP

### ISSUE THREAD

**Issue by kadamwhite** [WP-API/docs-v2#172]
May be a dupe, but still needs to be addressed. Helpful documentation taken from this thread on the main repo: WP-API/WP-API#2669

**Comment by BE-Webdesign** [comment]
As a note if you need to pass our special parameters like `_embed` and `_method` etc. you need to directly pass that in the `$_GET` superglobal as they are not checked in the request but instead in the PHP environment.

**Comment by kadamwhite** [comment]
Excellent working example was pasted into WP-API/WP-API#2857

**Comment by rmccue** [comment]
I added an example to https://developer.wordpress.org/reference/functions/rest_do_request/

**Comment by kadamwhite** [comment]
I've added a link to the rest_do_request documentation to the work-in-progress faq page
