### ISSUE TITLE
Can i Make a Chinese Copy?

### ISSUE THREAD

**Issue by bestony** [WP-API/docs-v2#182]
I will use this api,and i think maybe other need,so can i make a Chinese Copy? Or other  ways i can do for this project.

**Comment by kadamwhite** [comment]
@bestony We would absolutely love to have multi-lingual documentation, Chinese especially. However I understand from @kenshino that at this time there is not support on developer.wordpress.org for multi-lingual handbook material, so for now it may be best to write tutorials independently, as you have time and interest, and publish them through a blog. We can retroactively gather materials together if and when the handbook supports internationalization and localization!

**Comment by kadamwhite** [comment]
Closing this because we don't have a clear way forward; but if you do end up translating any http://developer.wordpress.org/rest-api handbook material and need a place to host it, feel free to open a new issue or PR so we can discuss
