### ISSUE TITLE
What's Changed: v2 Beta 1 page

### ISSUE THREAD

**Issue by kosso** [WP-API/docs-v2#187]
'What's Changed' links to a page referring to v2 Beta 1, along with recommendations about testing or production use.  http://v2.wp-api.org/changes-beta-1.html

Should this be updated, since we're on Beta 15 now, and in the core?

**Comment by kadamwhite** [comment]
This should have been done at the time, but now that the project has merged we're going to focus on documenting the actuality going forward.
