### ISSUE TITLE
Create User Guides section on developer.wordpress.org

### ISSUE THREAD

**Issue by kadamwhite** [WP-API/docs-v2#201]
The User Guides page should be an index of all available user guides, such as how

To write:

- [ ] How to filter collections, e.g. by search term, by `?slug`, or by `?tags=` or `?categories=`
- [ ] (possibly subset of above) How to retrieve posts matching a category by slug, by requesting the category by slug first and then making a request for posts w/ that category's ID
- [x] A list of available client libraries for working with the API from remote environments

**Comment by BE-Webdesign** [comment]
I think we should frame these in actual use cases as well, so there is a story/tangibility to what is demonstrated. From what I have seen on GitHub, most users are unclear and are usually surprised by how easy it is to do a common task with the API.  Getting posts by terms is an issue I see all of the time.

**Comment by kadamwhite** [comment]
The guides section has been created, I am going to split authoring these guides out into separate tickets

**Comment by kadamwhite** [comment]
See #207
