### ISSUE TITLE
Clarify HAL comment in rest handbook reference index

### ISSUE THREAD

**Issue by kadamwhite** [WP-API/docs-v2#210]
https://developer.wordpress.org/rest-api/reference/ should be updated to clarify the language around HAL.

Per @rmccue, we expose resource objects that follow the HAL spec, but the document is not a HAL document. See https://core.trac.wordpress.org/ticket/39453 as well.

**Comment by kadamwhite** [comment]
From [slack](https://wordpress.slack.com/archives/core-restapi/p1486418113003815), we should avoid "inspired by" because that's not accurate either, and instead say "we use the `_links` and `_embedded` properties from the HAL standard", which makes it clear what exactly we _do_ use

**Comment by kadamwhite** [comment]
@rmccue Here's what I've got:

## API Reference index page

> The REST API uses JSON exclusively as the request and response format, including error responses. While the REST API does not completely conform to the HAL standard, it does implement HAL’s `._links` and `._embedded` properties for linking API resources, and is fully discoverable via hyperlinks in the responses.

## Linking & Embedding page

> The WP REST API incorporates hyperlinking throughout the API to allow discoverability and browsability, as well as embedding related resources together in one response. While the REST API does not completely conform to the entire HAL standard, it implements the ._links and ._embedded properties from that standard as described below.

Sufficiently accurate?

**Comment by rmccue** [comment]
lgtm 👍

**Comment by kadamwhite** [comment]
Awesome. These changes are live on the handbook!
