### ISSUE TITLE
Clarify shortcomings of register_meta

### ISSUE THREAD

**Issue by kadamwhite** [WP-API/docs-v2#211]
https://developer.wordpress.org/rest-api/extending-the-rest-api/modifying-responses/ does not go into detail about the way register_meta( 'post'... will apply to _all_ post-derived objects. This is an omission brought up in [weekly chat](https://wordpress.slack.com/archives/C02RQC26G/p1491258091393066) that we should address

**Comment by garubi** [comment]
Also I think that should be explained if is wrong or right to use register_meta() instead of register_rest_field() when the meta field is intended to be used only with one or some custom posts (or taxonomies).

**Comment by kadamwhite** [comment]
I've added this section to the [Modifying Responses](https://developer.wordpress.org/rest-api/extending-the-rest-api/modifying-responses/) guide in the handbook: I'm going to mark this as resolved with this addition, we can re-open if further clarification is needed.

<h2>Using <code>register_rest_field</code> vs <code>register_meta</code></h2>

There are two methods which can be used to add data to WordPress REST API responses, <code>register_rest_field</code> and <code>register_meta</code>.

<code>register_rest_field</code> may be used to add arbitrary fields to any REST API response, and can be used to both read and write data using the API. To register a new REST field you must provide your own callback functions to get or set the field's value, as well as manually specify your own schema definition for the field.

<code>register_meta</code> is used to whitelist an existing custom meta value for access through the REST API. By setting a meta field's <code>show_in_rest</code> parameter to <code>true</code>, that field's value will be exposed on a <code>.meta</code> key in the endpoint response, and WordPress will handle setting up the callbacks for reading and writing to that meta key. This is much simpler than <code>register_rest_field</code>, with one caveat:

> [alert]
> Meta fields set to <code>show_in_rest</code> using <code>register_meta</code> are registered for all objects of a given type. If one custom post type shows a meta field, all custom post types will show that meta field.
> [/alert]

This is because meta registration is currently handled at the base level of WordPress object (post, user, etc) and cannot be specified per "subtype" (<strong>e.g.</strong> custom post types). <a href="https://core.trac.wordpress.org/ticket/38323">This limitation may be improved</a> in future versions of WordPress, but if you are trying to add a custom field to a specific API endpoint's response then <code>register_rest_field</code> is currently recommended over <code>register_meta</code>.
