### ISSUE TITLE
Document nonce-based authentication

### ISSUE THREAD

**Issue by danielbachhuber** [WP-API/docs-v2#25]
We have OAuth1 and Basic authentication documented. We should have some mention of the standard authentication cookies + nonce too that we can point to.

From https://github.com/WP-API/WP-API/issues/1311

**Comment by petenelson** [comment]
I believe it's already [documented here](https://github.com/WP-API/docs-v2/blob/gh-pages/guide/authentication/index.md#cookie-authentication) but I can also add the [_wp_rest_nonce](https://github.com/WP-API/WP-API/blob/bfaee003ad7e8d2454b0098afc2532e64a17fe42/extras.php#L117) parameter to the docs if you want to assign it to me.

**Comment by Shelob9** [comment]
Closing as "is documented"
