### ISSUE TITLE
Needs info about Wordpress version to use

### ISSUE THREAD

**Issue by kosso** [WP-API/docs-v2#33]
The download link on the home page says it needs Wordpress 4.3+, but no info on how to get that build.

**Comment by rmccue** [comment]
WordPress 4.3 is the latest beta version: https://wordpress.org/news/2015/07/wordpress-4-3-beta-3/

**Comment by kosso** [comment]
Thanks. Yes, but the documentation site does not make that clear. I had to ask, then wait for a reply, then install the Wordpress Beta Tester plugin to upgrade to the bleeding edge nightlies. The docs didn't mention that either. 

Also the big blue 'Download the plugin'  link on the documentation front page links to the old outdated page in the plugin directory.

**Comment by rmccue** [comment]
> Thanks. Yes, but the documentation site does not make that clear. I had to ask, then wait for a reply, then install the Wordpress Beta Tester plugin to upgrade to the bleeding edge nightlies. The docs didn't mention that either.

It's linked from the wordpress.org homepage, and the full release is coming up very shortly, so it's not a huge concern. The v2 plugin is still in beta, so having a slightly larger barrier to entry isn't a huge problem IMO.

> Also the big blue 'Download the plugin' link on the documentation front page links to the old outdated page in the plugin directory.

Working on it. :)
