### ISSUE TITLE
Front page search param is incorrect

### ISSUE THREAD

**Issue by caseydriscoll** [WP-API/docs-v2#57]
`GET /wp-json/wp/v2/posts?s=awesome` is incorrect, and the search query will be ignored.

`GET /wp-json/wp/v2/posts?filter[s]=awesome` is correct.

**Comment by danielbachhuber** [comment]
Let's keep this open until https://github.com/WP-API/WP-API/pull/1302 lands, as the parameter will eventually be `search`

**Comment by caseydriscoll** [comment]
Oh, groovy.

(Although, for what it's worth the current doc is wrong and sent me astray for 2 hours. Might mislead others as well while it is up. I know this is all a major WIP though)

**Comment by caseydriscoll** [comment]
Oh I see, you merged. :)

Gracias
