### ISSUE TITLE
Meta endpoint clarifications

### ISSUE THREAD

**Issue by danielbachhuber** [WP-API/docs-v2#60]
When we get around to adding documentation for the meta endpoints, we should mention:
1. Meta endpoints are only registered if the post type supports `custom-fields`. If the post type doesn't, the endpoints need to be manually registered https://github.com/WP-API/WP-API/issues/1637
2. Developers would be better off to add attributes to their resource, than using meta endpoints.

**Comment by kadamwhite** [comment]
Closing as meta handling best practices have moved towards register_meta
