### ISSUE TITLE
Document philosophy for adding actions and filters

### ISSUE THREAD

**Issue by danielbachhuber** [WP-API/docs-v2#61]
To have some consistency as to where we have actions and filters in the codebase, we should have a documented philosophy for when we add actions and filters (and when we don't).

**Comment by kadamwhite** [comment]
pattern had been to add them everywhere; this needs an owner to draft a proposal.

**Comment by kadamwhite** [comment]
Closing this because I'm not sure how it fits into the developer handbook; discussion of missing filters has moved to trac.
