### ISSUE TITLE
OAuth example code referenced doesn't work and is outdated

### ISSUE THREAD

**Issue by coderkevin** [WP-API/docs-v2#63]
On the Authentication page: http://v2.wp-api.org/guide/authentication/
Under "OAuth Authentication", an API Console: https://github.com/WP-API/api-console , is mentioned as a reference.

After spending a couple days trying to get it working, it became obvious to me that it wasn't designed for the v2 API, hasn't been updated in a year, and tries to do client-side authentication over OAuth sending a client key and secret in the clear from a JavaScript client.

I'd propose removing this reference link altogether as I don't feel it is a good starting place for people to learn how to use OAuth with the v2 API, and it teaches some really insecure practices that we should hope no one actually follows in their own application development.

**Comment by rmccue** [comment]
Totally correct; https://github.com/WP-API/rest-api-console is our v2 version, which doesn't use OAuth, but rather cookie authentication.

OAuth in JS is the only way to do client-side _only_ applications, but most apps will probably proxy via a server side instead. We should have an example that does that. :)

**Comment by kadamwhite** [comment]
Closing this as we're focusing on the built-in cookie authentication for the developer handbook, but this should be considered for documentation for the OAuth repo
