### ISSUE TITLE
Error when trying to serve documentation locally

### ISSUE THREAD

**Issue by kadamwhite** [WP-API/docs-v2#80]
I am getting this error when running `jekyll serve`:

```
Configuration file: /repos/wp-api/docs-v2/_config.yml
            Source: /repos/wp-api/docs-v2
       Destination: /repos/wp-api/docs-v2/_site
 Incremental build: disabled. Enable with --incremental
      Generating... 
  Dependency Error: Yikes! It looks like you don't have redcarpet or one of its dependencies installed. In order to use Jekyll as currently configured, you'll need to install this gem. The full error message from Ruby is: 'cannot load such file -- redcarpet' If you run into trouble, you can find helpful resources at http://jekyllrb.com/help/! 
  Conversion error: Jekyll::Converters::Markdown encountered an error while converting 'changes-beta-1.md':
                    redcarpet
             ERROR: YOUR SITE COULD NOT BE BUILT:
                    ------------------------------------
                    redcarpet
```

Versions:
- Ruby: 2.2.4p230
- jekyll: 3.0.1
- bundler: 1.11.2

**Comment by danielbachhuber** [comment]
I got this error too the last time I tried building docs locally :(

**Comment by rmccue** [comment]
Solution: install Redcarpet :)

```
sudo gem install redcarpet
```

This is documented in the Jekyll docs, IIRC?

**Comment by danielbachhuber** [comment]
After an hour or so of pain associated with trying to solve the dependency hell, I came across [this SO thread](http://stackoverflow.com/questions/31417469/jekyll-ruby-kramdown-missing-dependency).

`bundle exec jekyll serve --watch` works for me. @kadamwhite can you verify?

**Comment by kadamwhite** [comment]
Sorry for the lag, yes, `bundle exec jekyll serve` worked for me. Thanks!

**Comment by rmccue** [comment]
FWIW, I think the GH Pages gem is the officially supported best way to test locally, and I think that handles dependencies properly. Might be worth investigating.

**Comment by danielbachhuber** [comment]
> FWIW, I think the GH Pages gem is the officially supported best way to test locally

I have that installed too. Running through bundler means the appropriate versions of the dependencies are used.
