### ISSUE TITLE
Document how to modify authentication behavior at the application level

### ISSUE THREAD

**Issue by danielbachhuber** [WP-API/docs-v2#83]
Request from https://github.com/WP-API/WP-API/issues/1635#issuecomment-169697923

**Comment by kadamwhite** [comment]
Covered in the FAQ page at https://developer.wordpress.org/rest-api/using-the-rest-api/frequently-asked-questions/

**Comment by deltagm** [comment]
Hi,
are you sure that we need theses lines ?
```
if ( ! empty( $result ) ) {
        return $result;
    }
```
According to this https://gist.github.com/danielbachhuber/8f92af4c6a8db784771c#gistcomment-1968707
data are still available...
+ not used here:https://wordpress.org/plugins/disable-json-api/
Best regards
